<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            [ "name" => "United Arab Emirates", "code" => "ae", "code_long" => "ARE", "calling_code" => "971", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Afghanistan", "code" => "af", "code_long" => "AFG", "calling_code" => "93", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Antigua", "code" => "ag", "code_long" => "ATG", "calling_code" => "1268", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Anguilla", "code" => "ai", "code_long" => "AIA", "calling_code" => "1264", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Albania", "code" => "al", "code_long" => "ALB", "calling_code" => "355", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Armenia", "code" => "am", "code_long" => "ARM", "calling_code" => "374", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Netherlands Antilles", "code" => "an", "code_long" => "ANT", "calling_code" => "599", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Angola", "code" => "ao", "code_long" => "AGO", "calling_code" => "244", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Argentina", "code" => "ar", "code_long" => "ARG", "calling_code" => "54", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "American Samoa", "code" => "as", "code_long" => "ASM", "calling_code" => "1684", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Austria", "code" => "at", "code_long" => "AUT", "calling_code" => "43", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Australia", "code" => "au", "code_long" => "AUS", "calling_code" => "61", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Aruba", "code" => "aw", "code_long" => "ABW", "calling_code" => "297", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Azerbaijan", "code" => "az", "code_long" => "AZE", "calling_code" => "994", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Bosnia", "code" => "ba", "code_long" => "BIH", "calling_code" => "387", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Barbados", "code" => "bb", "code_long" => "BRB", "calling_code" => "1246", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Bangladesh", "code" => "bd", "code_long" => "BGD", "calling_code" => "880", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Belgium", "code" => "be", "code_long" => "BEL", "calling_code" => "32", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Burkina Faso", "code" => "bf", "code_long" => "BFA", "calling_code" => "226", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Bulgaria", "code" => "bg", "code_long" => "BGR", "calling_code" => "359", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Bahrain", "code" => "bh", "code_long" => "BHR", "calling_code" => "973", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Burundi", "code" => "bi", "code_long" => "BDI", "calling_code" => "257", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Benin", "code" => "bj", "code_long" => "BEN", "calling_code" => "229", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Bermuda", "code" => "bm", "code_long" => "BMU", "calling_code" => "1441", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Brunei", "code" => "bn", "code_long" => "BRN", "calling_code" => "673", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Bolivia", "code" => "bo", "code_long" => "BOL", "calling_code" => "591", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "Brazil", "code" => "br", "code_long" => "BRA", "calling_code" => "55", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "Bahamas", "code" => "bs", "code_long" => "BHS", "calling_code" => "1242", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Bhutan", "code" => "bt", "code_long" => "BTN", "calling_code" => "975", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Botswana", "code" => "bw", "code_long" => "BWA", "calling_code" => "267", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Belarus", "code" => "by", "code_long" => "BLR", "calling_code" => "375", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Belize", "code" => "bz", "code_long" => "BLZ", "calling_code" => "501", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Canada", "code" => "ca", "code_long" => "CAN", "calling_code" => "1", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Congo", "code" => "cd", "code_long" => "COD", "calling_code" => "243", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Central African Republic", "code" => "cf", "code_long" => "CAF", "calling_code" => "236", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Switzerland", "code" => "ch", "code_long" => "CHE", "calling_code" => "41", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Cote Divoire", "code" => "ci", "code_long" => "CIV", "calling_code" => "225", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Cook Islands", "code" => "ck", "code_long" => "COK", "calling_code" => "682", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Chile", "code" => "cl", "code_long" => "CHL", "calling_code" => "56", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "Cameroon", "code" => "cm", "code_long" => "CMR", "calling_code" => "237", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "China", "code" => "cn", "code_long" => "CHN", "calling_code" => "86", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Colombia", "code" => "co", "code_long" => "COL", "calling_code" => "57", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "Costa Rica", "code" => "cr", "code_long" => "CRI", "calling_code" => "506", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Serbia", "code" => "cs", "code_long" => "SRB", "calling_code" => "381", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Cuba", "code" => "cu", "code_long" => "CUB", "calling_code" => "53", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Cape Verde", "code" => "cv", "code_long" => "CPV", "calling_code" => "238", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Cyprus", "code" => "cy", "code_long" => "CYP", "calling_code" => "357", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Czech Republic", "code" => "cz", "code_long" => "CZE", "calling_code" => "420", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Germany", "code" => "de", "code_long" => "DEU", "calling_code" => "49", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Djibouti", "code" => "dj", "code_long" => "DJI", "calling_code" => "253", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Denmark", "code" => "dk", "code_long" => "DNK", "calling_code" => "45", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Dominica", "code" => "dm", "code_long" => "DMA", "calling_code" => "1767", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Dominican Republic", "code" => "do", "code_long" => "DOM", "calling_code" => "1809", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Algeria", "code" => "dz", "code_long" => "DZA", "calling_code" => "213", "continent" => "Africa", "mena" => TRUE ],
            [ "name" => "Ecuador", "code" => "ec", "code_long" => "ECU", "calling_code" => "593", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "Estonia", "code" => "ee", "code_long" => "EST", "calling_code" => "372", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Egypt", "code" => "eg", "code_long" => "EGY", "calling_code" => "20", "continent" => "Africa", "mena" => TRUE ],
            [ "name" => "Western Sahara", "code" => "eh", "code_long" => "ESH", "calling_code" => "212", "continent" => "Africa", "mena" => TRUE ],
            [ "name" => "Eritrea", "code" => "er", "code_long" => "ERI", "calling_code" => "291", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Spain", "code" => "es", "code_long" => "ESP", "calling_code" => "34", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Ethiopia", "code" => "et", "code_long" => "ETH", "calling_code" => "251", "continent" => "Africa", "mena" => TRUE ],
            [ "name" => "Finland", "code" => "fi", "code_long" => "FIN", "calling_code" => "358", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Fiji", "code" => "fj", "code_long" => "FJI", "calling_code" => "679", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Falkland Islands", "code" => "fk", "code_long" => "FLK", "calling_code" => "500", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "Faroe Islands", "code" => "fo", "code_long" => "FRO", "calling_code" => "298", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "France", "code" => "fr", "code_long" => "FRA", "calling_code" => "33", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Gabon", "code" => "ga", "code_long" => "GAB", "calling_code" => "241", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "United Kingdom", "code" => "gb uk", "code_long" => "GBR", "calling_code" => "44", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "England", "code" => "gb eng", "code_long" => "GBR", "calling_code" => "44", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Scotland", "code" => "gb sct", "code_long" => "GBR", "calling_code" => "44", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Wales", "code" => "gb wls", "code_long" => "GBR", "calling_code" => "44", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Grenada", "code" => "gd", "code_long" => "GRD", "calling_code" => "1473", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Georgia", "code" => "ge", "code_long" => "GEO", "calling_code" => "995", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "French Guiana", "code" => "gf", "code_long" => "GUF", "calling_code" => "594", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "Ghana", "code" => "gh", "code_long" => "GHA", "calling_code" => "233", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Gibraltar", "code" => "gi", "code_long" => "GIB", "calling_code" => "350", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Greenland", "code" => "gl", "code_long" => "GRL", "calling_code" => "299", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Gambia", "code" => "gm", "code_long" => "GMB", "calling_code" => "220", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Guinea", "code" => "gn", "code_long" => "GIN", "calling_code" => "224", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Guadeloupe", "code" => "gp", "code_long" => "GLP", "calling_code" => "590", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Equatorial Guinea", "code" => "gq", "code_long" => "GNQ", "calling_code" => "240", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Greece", "code" => "gr", "code_long" => "GRC", "calling_code" => "30", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Guatemala", "code" => "gt", "code_long" => "GTM", "calling_code" => "502", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Guam", "code" => "gu", "code_long" => "GUM", "calling_code" => "1671", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Guinea-bissau", "code" => "gw", "code_long" => "GNB", "calling_code" => "675", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Guyana", "code" => "gy", "code_long" => "GUY", "calling_code" => "592", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "Hong Kong", "code" => "hk", "code_long" => "HKG", "calling_code" => "852", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Honduras", "code" => "hn", "code_long" => "HND", "calling_code" => "504", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Croatia", "code" => "hr", "code_long" => "HRV", "calling_code" => "385", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Haiti", "code" => "ht", "code_long" => "HTI", "calling_code" => "509", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Hungary", "code" => "hu", "code_long" => "HUN", "calling_code" => "36", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Indonesia", "code" => "id", "code_long" => "IDN", "calling_code" => "62", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Ireland", "code" => "ie", "code_long" => "IRL", "calling_code" => "353", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Israel", "code" => "il", "code_long" => "ISR", "calling_code" => "972", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "India", "code" => "in", "code_long" => "IND", "calling_code" => "91", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Iraq", "code" => "iq", "code_long" => "IRQ", "calling_code" => "964", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Iran", "code" => "ir", "code_long" => "IRN", "calling_code" => "98", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Iceland", "code" => "is", "code_long" => "ISL", "calling_code" => "354", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Italy", "code" => "it", "code_long" => "ITA", "calling_code" => "39", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Jamaica", "code" => "jm", "code_long" => "JAM", "calling_code" => "1876", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Jordan", "code" => "jo", "code_long" => "JOR", "calling_code" => "962", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Japan", "code" => "jp", "code_long" => "JPN", "calling_code" => "81", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Kenya", "code" => "ke", "code_long" => "KEN", "calling_code" => "254", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Kyrgyzstan", "code" => "kg", "code_long" => "KGZ", "calling_code" => "996", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Cambodia", "code" => "kh", "code_long" => "KHM", "calling_code" => "855", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Kiribati", "code" => "ki", "code_long" => "KIR", "calling_code" => "686", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Comoros", "code" => "km", "code_long" => "COM", "calling_code" => "269", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Saint Kitts And Nevis", "code" => "kn", "code_long" => "KNA", "calling_code" => "1869", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "North Korea", "code" => "kp", "code_long" => "PRK", "calling_code" => "850", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "South Korea", "code" => "kr", "code_long" => "KOR", "calling_code" => "82", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Kuwait", "code" => "kw", "code_long" => "KWT", "calling_code" => "965", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Cayman Islands", "code" => "ky", "code_long" => "CYM", "calling_code" => "1345", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Kazakhstan", "code" => "kz", "code_long" => "KAZ", "calling_code" => "7", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Laos", "code" => "la", "code_long" => "LAO", "calling_code" => "856", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Lebanon", "code" => "lb", "code_long" => "LBN", "calling_code" => "961", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Saint Lucia", "code" => "lc", "code_long" => "LCA", "calling_code" => "1758", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Liechtenstein", "code" => "li", "code_long" => "LIE", "calling_code" => "423", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Sri Lanka", "code" => "lk", "code_long" => "LKA", "calling_code" => "94", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Liberia", "code" => "lr", "code_long" => "LBR", "calling_code" => "231", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Lesotho", "code" => "ls", "code_long" => "LSO", "calling_code" => "266", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Lithuania", "code" => "lt", "code_long" => "LTU", "calling_code" => "370", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Luxembourg", "code" => "lu", "code_long" => "LUX", "calling_code" => "352", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Latvia", "code" => "lv", "code_long" => "LVA", "calling_code" => "371", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Libya", "code" => "ly", "code_long" => "LBY", "calling_code" => "218", "continent" => "Africa", "mena" => TRUE ],
            [ "name" => "Morocco", "code" => "ma", "code_long" => "MAR", "calling_code" => "212", "continent" => "Africa", "mena" => TRUE ],
            [ "name" => "Monaco", "code" => "mc", "code_long" => "MCO", "calling_code" => "377", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Moldova", "code" => "md", "code_long" => "MDA", "calling_code" => "373", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Montenegro", "code" => "me", "code_long" => "MNE", "calling_code" => "382", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Madagascar", "code" => "mg", "code_long" => "MDG", "calling_code" => "261", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Marshall Islands", "code" => "mh", "code_long" => "MHL", "calling_code" => "692", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Macedonia", "code" => "mk", "code_long" => "MKD", "calling_code" => "389", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Mali", "code" => "ml", "code_long" => "MLI", "calling_code" => "223", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Burma", "code" => "mm", "code_long" => "MMR", "calling_code" => "95", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Mongolia", "code" => "mn", "code_long" => "MNG", "calling_code" => "976", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Macau", "code" => "mo", "code_long" => "MAC", "calling_code" => "853", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Northern Mariana Islands", "code" => "mp", "code_long" => "MNP", "calling_code" => "1670", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Martinique", "code" => "mq", "code_long" => "MTQ", "calling_code" => "596", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Mauritania", "code" => "mr", "code_long" => "MRT", "calling_code" => "222", "continent" => "Africa", "mena" => TRUE ],
            [ "name" => "Montserrat", "code" => "ms", "code_long" => "MSR", "calling_code" => "1664", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Malta", "code" => "mt", "code_long" => "MLT", "calling_code" => "356", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Mauritius", "code" => "mu", "code_long" => "MUS", "calling_code" => "230", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Maldives", "code" => "mv", "code_long" => "MDV", "calling_code" => "960", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Malawi", "code" => "mw", "code_long" => "MWI", "calling_code" => "265", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Mexico", "code" => "mx", "code_long" => "MEX", "calling_code" => "52", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Malaysia", "code" => "my", "code_long" => "MYS", "calling_code" => "60", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Mozambique", "code" => "mz", "code_long" => "MOZ", "calling_code" => "258", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Namibia", "code" => "na", "code_long" => "NAM", "calling_code" => "264", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "New Caledonia", "code" => "nc", "code_long" => "NCL", "calling_code" => "687", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Niger", "code" => "ne", "code_long" => "NER", "calling_code" => "227", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Norfolk Island", "code" => "nf", "code_long" => "NFK", "calling_code" => "6723", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Nigeria", "code" => "ng", "code_long" => "NGA", "calling_code" => "234", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Nicaragua", "code" => "ni", "code_long" => "NIC", "calling_code" => "505", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Netherlands", "code" => "nl", "code_long" => "NLD", "calling_code" => "31", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Norway", "code" => "no", "code_long" => "NOR", "calling_code" => "47", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Nepal", "code" => "np", "code_long" => "NPL", "calling_code" => "977", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Nauru", "code" => "nr", "code_long" => "NRU", "calling_code" => "674", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Niue", "code" => "nu", "code_long" => "NIU", "calling_code" => "683", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "New Zealand", "code" => "nz", "code_long" => "NZL", "calling_code" => "64", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Oman", "code" => "om", "code_long" => "OMN", "calling_code" => "968", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Panama", "code" => "pa", "code_long" => "PAN", "calling_code" => "507", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Peru", "code" => "pe", "code_long" => "PER", "calling_code" => "51", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "French Polynesia", "code" => "pf", "code_long" => "PYF", "calling_code" => "689", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "New Guinea", "code" => "pg", "code_long" => "PNG", "calling_code" => "675", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Philippines", "code" => "ph", "code_long" => "PHL", "calling_code" => "63", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Pakistan", "code" => "pk", "code_long" => "PAK", "calling_code" => "92", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Poland", "code" => "pl", "code_long" => "POL", "calling_code" => "48", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Puerto Rico", "code" => "pr", "code_long" => "PRI", "calling_code" => "1787", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Palestine", "code" => "ps", "code_long" => "PSE", "calling_code" => "970", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Portugal", "code" => "pt", "code_long" => "PRT", "calling_code" => "351", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Palau", "code" => "pw", "code_long" => "PLW", "calling_code" => "680", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Paraguay", "code" => "py", "code_long" => "PRY", "calling_code" => "595", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "Qatar", "code" => "qa", "code_long" => "QAT", "calling_code" => "974", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Reunion", "code" => "re", "code_long" => "REU", "calling_code" => "262", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Romania", "code" => "ro", "code_long" => "ROU", "calling_code" => "40", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Serbia", "code" => "rs", "code_long" => "SRB", "calling_code" => "381", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Russia", "code" => "ru", "code_long" => "RUS", "calling_code" => "7", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Rwanda", "code" => "rw", "code_long" => "RWA", "calling_code" => "250", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Saudi Arabia", "code" => "sa", "code_long" => "SAU", "calling_code" => "966", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Solomon Islands", "code" => "sb", "code_long" => "SLB", "calling_code" => "677", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Seychelles", "code" => "sc", "code_long" => "SYC", "calling_code" => "248", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Sudan", "code" => "sd", "code_long" => "SDN", "calling_code" => "249", "continent" => "Africa", "mena" => TRUE ],
            [ "name" => "Sweden", "code" => "se", "code_long" => "SWE", "calling_code" => "46", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Singapore", "code" => "sg", "code_long" => "SGP", "calling_code" => "65", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Slovenia", "code" => "si", "code_long" => "SVN", "calling_code" => "386", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Slovakia", "code" => "sk", "code_long" => "SVK", "calling_code" => "421", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Sierra Leone", "code" => "sl", "code_long" => "SLE", "calling_code" => "232", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "San Marino", "code" => "sm", "code_long" => "SMR", "calling_code" => "378", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Senegal", "code" => "sn", "code_long" => "SEN", "calling_code" => "221", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Somalia", "code" => "so", "code_long" => "SOM", "calling_code" => "252", "continent" => "Africa", "mena" => TRUE ],
            [ "name" => "Suriname", "code" => "sr", "code_long" => "SUR", "calling_code" => "597", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "El Salvador", "code" => "sv", "code_long" => "SLV", "calling_code" => "503", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Syria", "code" => "sy", "code_long" => "SYR", "calling_code" => "963", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Swaziland", "code" => "sz", "code_long" => "SWZ", "calling_code" => "268", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Caicos Islands", "code" => "tc", "code_long" => "TCA", "calling_code" => "1", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Chad", "code" => "td", "code_long" => "TCD", "calling_code" => "235", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Togo", "code" => "tg", "code_long" => "TGO", "calling_code" => "228", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Thailand", "code" => "th", "code_long" => "THA", "calling_code" => "66", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Tajikistan", "code" => "tj", "code_long" => "TJK", "calling_code" => "992", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Tokelau", "code" => "tk", "code_long" => "TKL", "calling_code" => "690", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Turkmenistan", "code" => "tm", "code_long" => "TKM", "calling_code" => "993", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Tunisia", "code" => "tn", "code_long" => "TUN", "calling_code" => "216", "continent" => "Africa", "mena" => TRUE ],
            [ "name" => "Tonga", "code" => "to", "code_long" => "TON", "calling_code" => "676", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Turkey", "code" => "tr", "code_long" => "TUR", "calling_code" => "90", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Trinidad", "code" => "tt", "code_long" => "TTO", "calling_code" => "868", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Tuvalu", "code" => "tv", "code_long" => "TUV", "calling_code" => "688", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Taiwan", "code" => "tw", "code_long" => "TWN", "calling_code" => "886", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Tanzania", "code" => "tz", "code_long" => "TZA", "calling_code" => "255", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Ukraine", "code" => "ua", "code_long" => "UKR", "calling_code" => "380", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Uganda", "code" => "ug", "code_long" => "UGA", "calling_code" => "256", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Us Minor Islands", "code" => "um", "code_long" => "UMI", "calling_code" => "246", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "United States", "code" => "us", "code_long" => "USA", "calling_code" => "1", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Uruguay", "code" => "uy", "code_long" => "URY", "calling_code" => "598", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "Uzbekistan", "code" => "uz", "code_long" => "UZB", "calling_code" => "998", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Vatican City", "code" => "va", "code_long" => "VAT", "calling_code" => "379", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Saint Vincent", "code" => "vc", "code_long" => "VCT", "calling_code" => "1784", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Venezuela", "code" => "ve", "code_long" => "VEN", "calling_code" => "58", "continent" => "South America", "mena" => FALSE ],
            [ "name" => "British Virgin Islands", "code" => "vg", "code_long" => "VGB", "calling_code" => "1284", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Us Virgin Islands", "code" => "vi", "code_long" => "VIR", "calling_code" => "1", "continent" => "North America", "mena" => FALSE ],
            [ "name" => "Vietnam", "code" => "vn", "code_long" => "VNM", "calling_code" => "84", "continent" => "Asia", "mena" => FALSE ],
            [ "name" => "Vanuatu", "code" => "vu", "code_long" => "VUT", "calling_code" => "678", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Wallis And Futuna", "code" => "wf", "code_long" => "WLF", "calling_code" => "681", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Samoa", "code" => "ws", "code_long" => "WSM", "calling_code" => "685", "continent" => "Oceania", "mena" => FALSE ],
            [ "name" => "Yemen", "code" => "ye", "code_long" => "YEM", "calling_code" => "967", "continent" => "Asia", "mena" => TRUE ],
            [ "name" => "Mayotte", "code" => "yt", "code_long" => "MYT", "calling_code" => "262", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "South Africa", "code" => "za", "code_long" => "ZAF", "calling_code" => "27", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Zambia", "code" => "zm", "code_long" => "ZMB", "calling_code" => "260", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Zimbabwe", "code" => "zw", "code_long" => "ZWE", "calling_code" => "263", "continent" => "Africa", "mena" => FALSE ],
            [ "name" => "Kosovo", "code" => "xk", "code_long" => "xks", "calling_code" => "383", "continent" => "Europe", "mena" => FALSE ],
            [ "name" => "Congo", "code" => "cd", "code_long" => "cod", "calling_code" => "242", "continent" => "Africa", "mena" => FALSE ]
        ];
        DB::table('countries')->insert($countries);
    }
}

